### ISSUE TITLE
attached PNG link doesn't render/work in github UI

### ISSUE THREAD

**Issue by craigcomstock** [nickanderson/cfengine-sysctl#3]
https://github.com/nickanderson/cfengine-sysctl/tree/master/policy/kernel-settings-sysctl-conf

has a link to https://github.com/nickanderson/cfengine-sysctl/blob/master/policy/kernel-settings-sysctl-conf/data/88/a9b1e8-418f-499c-96dd-6ff836ff821e/2021-10-11_12-46-01_2021-10-11_12-45-41.png 

but when rendered in github web UI the link leads nowhere. Maybe an org vs markdown issue?

**Comment by nickanderson** [comment]
Thanks, links by org-mode id don't work in github.
