### ISSUE TITLE
improve docs on variables to set in host specific data (kernel-settings-sysctl module)

### ISSUE THREAD

**Issue by craigcomstock** [nickanderson/cfengine-sysctl#4]
the readme here https://github.com/nickanderson/cfengine-sysctl/tree/master/policy/kernel-settings-sysctl-conf

has one typo. You need "default:" not "default_" here:

```
    e.g. default_kernel_settings_sysctl_conf._desired_conf_data_variable = data:variables.my_sysctl
```

I know you have a screenshot but I think it would be more helpful to have text in your README along with some explanation or references on namespace of host specific data versus augments and such.

In order to use host specific data you must set the following variables. The exact names are important due to the different namespaces that exist for variables. In this example you wish to store sysctl values in a data container variable named my_sysctl.

The line

```
e.g. data:variables.my_sysctl = ={ “vm.swappiness”: “10”, “fs.protected_hardlinks”: “1”,
```

if used in host specific data in Mission Portal won't work, as the name of the variable should be just `my_sysctl`. I suppose the example you give would work if in augments.

**Comment by nickanderson** [comment]
Thanks, typo fixed.

Added an example showing the raw text for setting variables.

Note, if you use the FULL variable name in Mission Portal it works fine, if you use an unqualified variable it should still work.
